<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9S969CC" failures="0" tests="6" name="com.testingshashtra.regression.ParameterTestCase" time="6.090" errors="2" timestamp="2023-09-15T16:17:37 IST" skipped="0">
  <testcase classname="com.testingshashtra.regression.ParameterTestCase" name="thirdTestCase" time="3.030">
    <error message="Method com.testingshashtra.regression.ParameterTestCase.thirdTestCase() didn&#039;t finish within the time-out 3000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testingshashtra.regression.ParameterTestCase.thirdTestCase() didn't finish within the time-out 3000
at java.base@17.0.6/java.lang.Thread.sleep(Native Method)
at app//com.testingshashtra.regression.ParameterTestCase.thirdTestCase(ParameterTestCase.java:32)
at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.6/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- thirdTestCase -->
  <testcase classname="com.testingshashtra.regression.ParameterTestCase" name="testCaseFirst" time="0.004"/>
  <testcase classname="com.testingshashtra.regression.ParameterTestCase" name="m1" time="0.023"/>
  <testcase classname="com.testingshashtra.regression.ParameterTestCase" name="m2" time="3.013">
    <error message="
Method ParameterTestCase.m2()[pri:0, instance:com.testingshashtra.regression.ParameterTestCase@942a29c] should have thrown an exception of any of types [class java.lang.ArrayIndexOutOfBoundsException, class java.lang.RuntimeException]" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method ParameterTestCase.m2()[pri:0, instance:com.testingshashtra.regression.ParameterTestCase@942a29c] should have thrown an exception of any of types [class java.lang.ArrayIndexOutOfBoundsException, class java.lang.RuntimeException]
at org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)
at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:860)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:718)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- m2 -->
  <testcase classname="com.testingshashtra.regression.ParameterTestCase" name="m1" time="0.007"/>
  <testcase classname="com.testingshashtra.regression.ParameterTestCase" name="m1" time="0.013"/>
</testsuite> <!-- com.testingshashtra.regression.ParameterTestCase -->
